openapi: 3.0.0
tags:
  - name: models
  - name: Question
  - name: Tag
  - name: Authentication
info:
  title: Admin API
  version: v1.0.0
  license:
    name: Trivia
    url: 'https://www.viaapi.com/legal/licensing/trivia'
  contact:
    name: System Administrator
    email: admin@viaapi.com
    url: 'https://www.viaapi.com'
  termsOfService: 'https://www.viaapi.com/legal/tos/trivia'
  description: This documentation covers all admin endpoints.
servers:
  - url: 'https://trivia.admin.api.viaapi.com/v1'
    description: Production
  - url: 'https://trivia.admin.api.dev.viaapi.com/v1'
    description: Development / Testing Server
paths:
  /login:
    post:
      summary: 'POST :: /login'
      operationId: admin-post-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example:
                  value:
                    code: '200.0401'
                    message: You have been successfully logged in.
                    result:
                      pagination: 'null'
                      set:
                        id: 32
                        uuid: 095be615-a8ad-4c33-8e9c-c7612fbf6c9f
                        status: a
                        email: support@viaapi.com
                        firstName: John
                        middleName: Johnny Johnathan
                        lastName: Johannesson
                        isSuper: true
                        roles:
                          - ROLE_TQ_MCS_APPROVE
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0002:
                  value:
                    code: '401.0002'
                    message: 'Please check your username and password, and try again.'
                    result:
                      pagination: null
                      set: null
                    sessionToken: null
                Example-0003:
                  value:
                    code: '401.0003'
                    message: You have failed to login many times. Your account is susspended for 2 hours. You have been sent a security key to your primary contact option. You can either wait 2 hours or you can follow the instructions provided.
                    result:
                      pagination: null
                      set: null
                    sessionToken: null
      description: |-
        Use this endpoint to authenticate a real admin user into the UI/panel.

        ### Flow
        ![Flow](https://docs-viaapi.s3.amazonaws.com/flow-charts/admin.post.login.png)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginForm'
            examples:
              Example:
                value:
                  email: member@maildrop.cc
                  password: 123verysecure321...
                  termsAccepted: true
        description: ''
      parameters: []
      tags:
        - Authentication
      security:
        - X-Session-Key: []
  '/questions/{region}/mc/sa':
    get:
      summary: 'GET :: /questions/{region}/mc/sa'
      responses:
        '200':
          description: Successful response.
          headers: {}
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0000:
                  value:
                    code: '200.0000'
                    message: Your request has been successfully completed.
                    result:
                      pagination:
                        isCircular: true
                        prevLink: null
                        nextLink: offset=10&limit=10
                        lastLink: offset=90&limit=10
                        firstLink: offset=0&limit=10
                        totalItems: 1000
                        filteredItems: 100
                        itemsPerPage: 10
                        pageCount: 10
                        currentPage: 1
                      set:
                        - id: 5f7ae654f49cb6078151b14a
                          createdAt: '2020-10-05 09:24:21'
                          updatedAt: '2020-10-05 09:24:21'
                          status: w
                          banner: null
                          choices:
                            - isCorrect: false
                              label:
                                text: Finike
                                audio: null
                                image: null
                                video: null
                            - isCorrect: false
                              label:
                                text: Alanya
                                audio: null
                                image: null
                                video: null
                            - isCorrect: true
                              label:
                                text: Demre
                                audio: null
                                image: null
                                video: null
                            - isCorrect: false
                              label:
                                text: Aksu
                                audio: null
                                image: null
                                video: null
                          difficultyLevel: 6
                          estimatedReadTime: 32
                          tags:
                            - id: 5f7ae645f49cb6078151b135
                              createdAt: '2020-10-05 09:24:21'
                              updatedAt: '2020-10-05 09:24:21'
                              status: w
                              icon: null
                              itemCount: 0
                              title: myth
                          label:
                            text: Noel Baba efsanesinin Antalya'nın hangi ilçesinde yaşayan Psikopos Nikola'ya dayandığı düşünülmektedir?
                            audio: null
                            image: null
                            video: null
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
                Example-0404:
                  value:
                    code: '200.0404'
                    message: No recods found matching your criteria.
                    result:
                      pagination: 'null'
                      set: 'null'
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0001:
                  value:
                    code: '401.0001'
                    message: Your session is expired. Please re-login.
                    result:
                      pagination: 'null'
                      set: 'null'
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
        '412':
          description: Precondition Failed
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0000:
                  value:
                    code: '412.0000'
                    message: '"limit" parameter must be an integer value between 1 and 200.'
                    result:
                      pagination: 'null'
                      set: 'null'
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
                Example-0002:
                  value:
                    code: '412.0002'
                    message: '"order" parameter has one or more unsupported operands. See related documentation for more information.'
                    result:
                      pagination: 'null'
                      set: 'null'
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
                Example-0003:
                  value:
                    code: '412.0003'
                    message: '"order" parameter has one or more unsupported options. See related documentation for more information.'
                    result:
                      pagination: 'null'
                      set: 'null'
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
                Example-9999:
                  value:
                    code: '412.9999'
                    message: 'The value, operands, or options are not valid for the createdAt. Please check related documentatiofor more information.'
                    result:
                      pagination: 'null'
                      set: 'null'
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
                Example-0001:
                  value:
                    code: '412.0001'
                    message: '"offset" parameter has one or more unsupported operands. See related documentation for more information.'
                    result:
                      pagination: 'null'
                      set: 'null'
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
      operationId: admin-get-questions-mc-sa
      description: |-
        This endpoint provides a list of "multi-choice single correct answer" trivia questions. You can summon data filtered by the following properties:
        - difficulty level
        - reading time
        - tags
        - status
        - creation time
        - update time

        You can search data based on the following properties:
        - label of question
        - label of choices

        This endpoint only provides the most up-to-date version of each document.

        <!-- theme: danger -->
        > ### ROLE REQUIREMENT
        > 
        > This endpoint needs **ROLE_TRIVIA_GRANTED_APP** at session.

        ### Flow
        ![Flow](https://docs-viaapi.s3.amazonaws.com/flow-charts/admin.get.questions.mc.sa.png)
      security:
        - X-Session-Key: []
      parameters:
        - schema:
            type: integer
            default: '50'
            maximum: 200
            minimum: 1
            exclusiveMinimum: false
          in: query
          name: limit
          description: |-
            Number of items to be returned. No more than 200 items can be returned at one query.<br />
            **Example:**
            ?limit=100
        - schema:
            type: integer
            minimum: 0
            default: '0'
          in: query
          name: offset
          description: |-
            The start point / row of the entries to be listed.<br />

            **Example:**
            ?offset=0
        - schema:
            type: array
            items:
              type: string
            maxItems: 0
            minItems: 0
            uniqueItems: false
          in: query
          name: order
          description: |-
            This parameter dictates the order of list.<br />
            **Operands:**<br />
            - `+`: ASCENDING
            - `-`: DESCENDING<br />
            **Available Options:**<br />
            - createdAt
            - updatedAt
            - id
            - difficultyLevel
            - label.text
            **Example:**<br />
            Sort questions by their labels ascending and by their creation time descending.<br />
            ?order[]=+label.text&order[]=-dateCreated
        - schema:
            type: array
            items:
              type: string
          in: query
          name: status
          description: |-
            This parameter is used to filter questions by their statuses.<br />

            **Example:**
            Only retrieve questions with status "a" or "w".<br />

            ?status[]=a&status[]=w
        - schema:
            type: array
            items:
              type: string
            minItems: 1
            maxItems: 2
          in: query
          name: createdAt
          description: |-
            This parameter is used to filter entries by their creation times.<br />
            **Acceptable Date Formats**:<br />
            - YYYY-MM-DD
            - YYYY-MM-DD HH:ii:ss<br />
            **Operands**:<br />
            - eq: Equal
            - gt: Greater Than
            - gte: Greater Than or Equal
            - lt: Less Than
            - lte: Less Than or Equal
            - nq: Not Equal
            - in: In
            - nin: Not In<br />
            **Example**:
            List entries created at 27th of January 2020.<br />

            ?createdAt[[eq]]=2020-01-27<br />

            List entries created between 21st and 27th of January 2020, both dates inclusive.<br />
            ?createdAt[[gte]]=2020-01-21&createdAt[[lte]]=2020-01-27<br>

            <!-- theme: warning -->
            > **Alternative Usage**
            > 
            > Also we can use **?createdAt={"eq": "2020-01-21"}**
        - schema:
            items:
              type: string
              format: date-time
            type: array
          in: query
          name: updatedAt
          description: |-
            This parameter is used to filter entries by their update times.<br />
            **Acceptable Date Formats**:<br />
            - YYYY-MM-DD
            - YYYY-MM-DD HH:ii:ss<br />
            **Operands**:<br />
            - eq: Equal
            - gt: Greater Than
            - gte: Greater Than or Equal
            - lt: Less Than
            - lte: Less Than or Equal
            - nq: Not Equal<br />
            **Example**:
            List entries updated at 27th of January 2020.<br />

            ?updatedAt[[eq]]=2020-01-27<br />

            List entries updated between 21st and 27th of January 2020, both dates inclusive.<br />
            ?updatedAt[[gte]]=2020-01-21&updatedAt[[lte]]=2020-01-27<br>

            <!-- theme: warning -->
            > **Alternative Usage**
            > 
            > Also we can use **?updatedAt={"eq": "2020-01-21"}**
        - schema:
            type: array
            items:
              type: integer
          in: query
          name: difficultyLevel
          description: |-
            This parameter is used to filter entries by their difficulty level.<br />
            **Operands**:<br />
            - eq: Equal
            - gt: Greater Than
            - gte: Greater Than or Equal
            - lt: Less Than
            - lte: Less Than or Equal
            - nq: Not Equal
            - in: Use to summon arbitrary data.<br />
            **Example**:
            List entries marked with a difficulty level of 9.<br />

            ?difficultyLevel[[eq]]=9<br />

            List entries marked with a difficulty level between 2 and 4 inclusive.<br />
            ?difficultyLevel[[gte]]=2&createdAt[[lte]]=4

            List entries marked with a difficulty level of 3, 5 and 8.<br />
            ?difficultyLevel[[in]]=3,5,8<br>

            <!-- theme: warning -->
            > **Alternative Usage**
            > 
            > Also we can use **?difficultyLevel={"in": "3,5,8"}**
        - schema:
            type: array
            items:
              type: integer
          in: query
          name: estimatedReadingTime
          description: |-
            This parameter is used to filter entries by their estimated reading time.<br />
            **Operands**:<br />
            - eq: Equal
            - gt: Greater Than
            - gte: Greater Than or Equal
            - lt: Less Than
            - lte: Less Than or Equal
            - nq: Not Equal<br />
            **Example**:
            List entries that can be read within 30 seconds.<br />

            ?estimatedReadingTime[[eq]]=30<br />

            List entries that can be read less than 30 seconds.<br />
            ?estimatedReadingTime[[lt]]=30<br />

            List entriesthat can be read beween 30 to 60 seconds inclusive<br />
            ?estimatedReadingTime[[gte]]=30&estimatedReadingTime[[lte]]=60<br>

            <!-- theme: warning -->
            > **Alternative Usage**
            > 
            > Also we can use **?estimatedReadingTime={"gte": 30, "lte": 60}**
        - schema:
            type: array
            items:
              type: string
          in: query
          name: q
          description: |-
            This parameter is used to run a search within the question or choice labels.<br />
            **Keys**:<br />
            - cho: choice
            - qst: question<br />
            **Operands**:<br />
            - `*`: Wildcard<br />
            **Example**:
            Search questions with choice labels starting with "Bruce".<br />
            ?q[[cho]][]=Bruce\*

            Search questions with labels include "Batman"<br />
            ?q[[qst]][]=\*Batman\*

            Search questions with labels include "Batman" and with choice labels equal to "Michael Keaton"<br />
            ?q[[qst]][]=\*Batman\*&q[[cho]][]=Michael%20Keaton<br>

            <!-- theme: warning -->
            > **Alternative Usage**
            > 
            > Also we can use **?q={"cho": ["Batman"], "qst": ["Batman"]}**
        - schema:
            type: array
          in: query
          name: tags
          description: |-
            This parameter is used to filter entries by their tags.<br />
            **Operands**:<br />
            - eq: Equal
            - gt: Greater Than
            - gte: Greater Than or Equal
            - lt: Less Than
            - lte: Less Than or Equal
            - nq: Not Equal
            - in: Use to summon arbitrary data.<br />

            **Example**:
            List entriestagged with tag of id 9.<br />

            ?tags[[eq]]=9

            List entries taged with a tags of ids 3, 5 or 8.<br />
            ?tags[[in]]=3,5,8<br>

            <!-- theme: warning -->
            > **Alternative Usage**
            > 
            > Also we can use **?tags={"in": "3,5,8"}**
      tags:
        - Question
    parameters:
      - schema:
          type: string
          enum:
            - tr-tr
            - en-use
          default: tr-tr
        name: region
        in: path
        required: true
        description: 'see [documentation](https://archbee.io/public/3geArFXiTaFdM3kcfky7E/region-codes)'
  '/tags/{region}':
    get:
      summary: 'GET :: /tags/{region}'
      responses:
        '200':
          description: Successful response.
          headers: {}
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example:
                  value:
                    code: '200.0000'
                    message: ''
                    result:
                      pagination:
                        isCircular: true
                        prevLink: null
                        nextLink: offset=10&limit=10
                        lastLink: offset=90&limit=10
                        firstLink: offset=0&limit=10
                        totalItems: 1000
                        filteredItems: 100
                        itemsPerPage: 10
                        pageCount: 10
                        currentPage: 1
                    set:
                      - icon: soccer.svg
                        title: soccer
                        itemCount: 2322
                        uuid: b914edfb-dadb-49f0-a729-08e882987e38
                      - icon: history.svg
                        title: history
                        itemCount: 342
                        uuid: 91bf5e5a-be48-400c-ac57-8c4dfdc6b283
      operationId: admin-get-tags
      description: |-
        This endpoint returns a list of tags (TQTag objects) that are used to classify trivia tags.

        <!-- theme: danger -->
        > ### ROLE REQUIREMENT
        >
        > This endpoint needs **ROLE_TRIVIA_GRANTED_APP** at session.

        ### Flow
        ![Flow](https://docs-viaapi.s3.amazonaws.com/flow-charts/admin.get.tags.png)
      parameters:
        - schema:
            type: integer
            default: '50'
            maximum: 200
            minimum: 1
            exclusiveMinimum: false
          in: query
          name: limit
          description: |-
            Number of items to be returned. No more than 200 items can be returned at one query.<br/>
            **Example:**
            ?limit=100
        - schema:
            type: integer
            minimum: 0
            default: '0'
          in: query
          name: offset
          description: |-
            The start point / row of the entries to be listed.<br/>

            **Example:**
            ?offset=0
        - schema:
            type: array
            items:
              type: string
            maxItems: 0
            minItems: 0
            uniqueItems: false
          in: query
          name: order
          description: |-
            This parameter dictates the order of list.<br/>
            **Operands:**<br/>
            - `+`: ASCENDING
            - `-`: DESCENDING<br/>
            **Available Options:**<br/>
            - createdAt
            - updatedAt
            - title
            - itemCount<br/>
            **Example:**<br/>
            Sort data by their title ascending and by their creation time descending.<br/>
            ?order[]=+title&order[]=-createdAt
        - schema:
            type: array
            items:
              type: string
          in: query
          name: status
          description: |-
            This parameter is used to filter questions by their statuses.<br/>

            **Example:**
            Only retrieve questions with status "a" or "w".<br/>

            ?status[]=a&status[]=w
        - schema:
            type: array
            items:
              type: string
            minItems: 1
            maxItems: 2
          in: query
          name: createdAt
          description: |-
            This parameter is used to filter entries by their creation times.<br/>
            **Acceptable Date Formats**:
            - YYYY-MM-DD
            - YYYY-MM-DD HH:ii:ss

            **Operands**:
            - eq: Equal
            - gt: Greater Than
            - gte: Greater Than or Equal
            - lt: Less Than
            - lte: Less Than or Equal
            - nq: Not Equal
            - in: In
            - nin: Not In<br/>
            **Example**:
            List entries created at 27th of January 2020.<br/>

            ?createdAt[[eq]]=2020-01-27<br/>

            List entries created between 21st and 27th of January 2020, both dates inclusive.<br/>
            ?createdAt[[gte]]=2020-01-21&createdAt[[lte]]=2020-01-27<br>

            <!-- theme: warning -->
            > **Alternative Usage**
            > 
            > Also we can use **?createdAt={"eq": "2020-01-21"}**
        - schema:
            items:
              type: string
              format: date-time
            type: array
          in: query
          name: updatedAt
          description: |-
            This parameter is used to filter entries by their update times.<br/>
            **Acceptable Date Formats**:<br/>
            - YYYY-MM-DD
            - YYYY-MM-DD HH:ii:ss<br/>
            **Operands**:<br/>
            - eq: Equal
            - gt: Greater Than
            - gte: Greater Than or Equal
            - lt: Less Than
            - lte: Less Than or Equal
            - nq: Not Equal<br/>
            **Example**:
            List entries updated at 27th of January 2020.<br/>

            ?updatedAt[[eq]]=2020-01-27<br/>

            List entries updated between 21st and 27th of January 2020, both dates inclusive.<br/>
            ?updatedAt[[gte]]=2020-01-21&updatedAt[[lte]]=2020-01-27<br>

            <!-- theme: warning -->
            > **Alternative Usage**
            > 
            > Also we can use **?updatedAt={"eq": "2020-01-21"}**
        - schema:
            type: array
            items:
              type: string
          in: query
          name: q
          description: |-
            This parameter is used to run a search within the question or choice labels.<br/>
            **Keys**:
            - title: title<br/>
            **Operands**:<br/>
            - `*`: Wildcard
            **Example**:<br/>
            Search tags with title starting with "hist".<br/>
            ?q[[title]][]=hist\*
            Search tags with labels include "tera"<br/>
            ?q[[title]][]=\*tera\*<br/>
            Search tags with titles include "tera" or with title equal to "literature"<br/>
            ?q[[title]][]=\*tera\*&q[[title]][]=literature<br/>

            <!-- theme: warning -->
            > **Alternative Usage**<br/>
            > Also we can use **?q={"title": [["tera*"]]}**
        - schema:
            type: array
          in: query
          name: itemCount
          description: |-
            This parameter is used to filter entries by item counts.<br/>

            **Operands**:<br/>
            - eq: Equal
            - gt: Greater Than
            - gte: Greater Than or Equal
            - lt: Less Than
            - lte: Less Than or Equal<br/>

            **Example**:<br/>
            List entries with item counts between 5 and 10.<br/>

            ?itemCount[[gte]]=5&itemCount[[lte]]=10<br>

            <!-- theme: warning -->
            > **Alternative Usage**
            > 
            > Also we can use **?itemCount={"gte": "5", "lte": 10}**
      tags:
        - Tag
      security:
        - X-Session-Key: []
    parameters:
      - schema:
          type: string
          enum:
            - tr-tr
            - tr-nc
            - ru-ru
            - es-es
            - fr-fr
            - es-ln
            - es-xx
            - en-xx
            - en-us
            - en-uk
            - de-at
            - de-de
          default: tr-tr
          example: tr-tr
        name: region
        in: path
        required: true
        description: 'see [documentation](https://archbee.io/public/3geArFXiTaFdM3kcfky7E/region-codes)'
  '/question/{region}/mc/sa/{uuid}':
    parameters:
      - schema:
          type: string
        name: uuid
        in: path
        required: true
        description: System attained id of the question.
      - schema:
          type: string
          enum:
            - tr-tr
            - en-us
          default: tr-tr
        name: region
        in: path
        required: true
        description: 'see [documentation](https://api.docs.viaapi.com/Cxem-region-codes)'
    put:
      summary: 'PUT :: /question/{region}/mc/sa/{uuid}'
      operationId: admin-put-questions-mc-sa-uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example:
                  value:
                    code: '200.0000'
                    message: Your request has been successfully completed.
                    result:
                      pagination: null
                      set: 231
                    sessionToken: null
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0001:
                  value:
                    code: '401.0001'
                    message: ''
                    result:
                      pagination: null
                      set: Your session is expired. Please re-login.
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
        '412':
          description: Precondition Failed
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-9995:
                  value:
                    code: '401.7000'
                    message: 'You have supplied an invalid data. Please check releated documentation, fix all your issues and try again. If the problem persists, you can contact our support team.'
                    result:
                      pagination: null
                      set: null
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
                Example-0100:
                  value:
                    code: '412.0100'
                    message: Preliminary data validation failed. Please check related service documentation.
                    result:
                      pagination: null
                      set: null
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
      description: |-
        This endpoint is used to update an existing multi-choice single answer trivia question entry.

        <!-- theme: warning -->
        > ### WARNING
        >
        > A trivia editor (NOT ADMIN) can only edit the same question a maximum of 3 times in 120 minutes.

        > ### ROLE REQUIREMENT
        >
        > This endpoint needs **ROLE_TRIVIA_QUESTION_UPDATE** at session.

        ### Flow
        ![Flow](https://docs-viaapi.s3.amazonaws.com/flow-charts/admin.put.question.mc.sa.uuid.png)
      security:
        - X-Session-Key: []
      parameters:
        - schema:
            type: string
          in: query
          name: uuid
          description: The UUID of the entry to be updated. This is used as an extra security measure and it should be equal to the UUID of the object provided within the request body.
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./TriviaModels/TQMultiChoiceSingleVersionUpdate.v1.yaml
            examples:
              Example:
                value:
                  uuid: cfc21291-18f6-47cf-b714-ed87d150c076
                  status: a
                  banner:
                    path: batman-logo.jpg
                    type: i
                  difficultyLevel: 1
                  estimatedReadTime: 50
                  tags:
                    - title: movies
                      icon: movies.png
                      itemCount: 234
                  label:
                    audio: question-223423-2342342-2342.mp3
                    video: question-223423-2342342-2342.mp4
                    image: batman-logo.jpg
                    text: Who among these Hollywood stars have not played the Batman character?
      tags:
        - Question
    delete:
      summary: 'DELETE :: /question/{region}/mc/sa/{uuid}'
      operationId: admin-delete-questions-mc-sa-uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example:
                  value:
                    code: '200.0000'
                    message: Your request has been successfully completed.
                    result:
                      pagination: null
                      set: true
                    sessionToken: null
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-00001:
                  value:
                    code: '401.0001'
                    message: Your session is expired. Please re-login.
                    result:
                      pagination: null
                      set: null
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
                Example-9000:
                  value:
                    code: '401.9000'
                    message: You do not have enough permissions to access this feature.
                    result:
                      pagination: null
                      set: null
                    sessionToken: null
        '412':
          description: Precondition Failed
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0100:
                  value:
                    code: '412.0100'
                    message: Preliminary data validation failed. Please check related service documentation.
                    result:
                      pagination: null
                      set: null
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
                Example-9995:
                  value:
                    code: '412.9995'
                    message: The supplied path parameter is invalid or a required path parameter is missing.
                    result:
                      pagination: null
                      set: null
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
      description: |-
        This endpoint is used to mark an existing entry as "deleted".

        <!-- theme: danger -->
        > ### ROLE REQUIREMENT
        >
        > This endpoint needs **ROLE_TRIVIA_QUESTION_DELETE** at session.

        ### Flow
        ![Flow](https://docs-viaapi.s3.amazonaws.com/flow-charts/admin.delete.question.mc.sa.uuid.png)
      security:
        - X-Session-Key: []
      parameters: []
      tags:
        - Question
    get:
      summary: 'GET :: /question/{region}/mc/sa/{uuid}'
      operationId: admin-get-questions-mc-sa-uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0000:
                  value:
                    code: '200.0000'
                    message: Your request has been successfully completed.
                    result:
                      pagination: null
                      set:
                        uuid: cfc21291-18f6-47cf-b714-ed87d150c076
                        dateCreated: '2020-01-20T12:23:24Z'
                        dateUpdated: '2020-01-21T21:23:12Z'
                        status: a
                        banner:
                          path: batman-logo.jpg
                          type: i
                        difficultyLevel: 1
                        estimatedReadTime: 50
                        tags:
                          - title: movies
                            icon: movies.png
                            itemCount: 234
                        label:
                          audio: question-223423-2342342-2342.mp3
                          video: question-223423-2342342-2342.mp4
                          image: batman-logo.jpg
                          text: Who among these Hollywood stars have not played the Batman character?
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
                Example-0404:
                  value:
                    code: '200.0404'
                    message: No recods found matching your criteria.
                    result:
                      pagination: null
                      set: null
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0001:
                  value:
                    code: '401.0001'
                    message: Your session is expired. Please re-login.
                    result:
                      pagination: null
                      set: null
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
        '412':
          description: Precondition Failed
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-9995:
                  value:
                    code: '412.9995'
                    message: The supplied path parameter is invalid or a required path parameter is missing.
                    result:
                      pagination: null
                      set: null
                    sessionToken: null
      description: |-
        This endpoint is used to retrieve a selected multi-choice single answer trivia question.

        <!-- theme: danger -->

        > ### ROLE REQUIREMENT
        >
        > This endpoint needs **ROLE_TRIVIA_QUESTION_DISPLAY** at session.

        ### Flow
        ![Flow](https://docs-viaapi.s3.amazonaws.com/flow-charts/admin.get.question.mc.sa.uuid.png)
      security:
        - X-Session-Key: []
      tags:
        - Question
  '/question/{region}/mc/sa/{uuid}/status/{status}':
    parameters:
      - schema:
          type: string
        name: uuid
        in: path
        required: true
        description: UUID of the entry which is being updated.
      - schema:
          type: string
          enum:
            - a
            - d
            - i
            - r
            - w
        name: status
        in: path
        required: true
        description: |-
          Value of new status.

          Allowed values are:

          - a: active (approved)
          - d: deleted
          - i: inactive (approved but unpublished)
          - r: rejected
          - w: waiting for approval

          NOTE THAT values a, d, i, r can only be set by users with right permissions.
      - schema:
          type: string
          default: tr-tr
          enum:
            - tr-tr
            - en-us
        name: region
        in: path
        required: true
        description: 'see [documentation](https://api.docs.viaapi.com/Cxem-region-codes)'
    patch:
      summary: 'PATCH :: /question/{region}/mc/sa/{uuid}/status/{status}'
      operationId: admin-patch-questions-mc-sa-uuid-status-status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0404:
                  value:
                    code: '200.0404'
                    message: No recods found matching your criteria.
                    result:
                      pagination: null
                      set: null
                    sessionToken: null
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-9000:
                  value:
                    code: '412.9000'
                    message: You do not have enough permissions to access this feature.
                    result:
                      pagination: null
                      set: null
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
        '412':
          description: Precondition Failed
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0100:
                  value:
                    code: '412.0100'
                    message: Preliminary data validation failed. Please check related service documentation.
                    result:
                      pagination: null
                      set: null
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
      description: |-
        This endpoint is used to update status of the question entry.

        - a: approved & activated
        - d: deleted
        - i: inactive

        <!-- theme: danger -->
        > ### ROLE REQUIREMENT
        >
        > This endpoint needs **ROLE_TRIVIA_QUESTION_UPDATE_STATUS** at session.

        ### Flow
        ![Flow](https://docs-viaapi.s3.amazonaws.com/flow-charts/admin.patch.question.mc.sa.uuid.status.status.png)
      security:
        - X-Session-Key: []
      parameters:
        - schema:
            type: string
            enum:
              - a
              - i
              - d
          in: query
          name: status
          description: The new status of the entry.
          required: true
      tags:
        - Question
  '/question/{region}/mc/sa':
    parameters:
      - schema:
          type: string
        name: region
        in: path
        required: true
    post:
      summary: 'POST :: /question/{region}/mc/sa'
      operationId: admin-post-question-region-mc-sa
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0000:
                  value:
                    code: '200.0000'
                    message: Your request has been successfully completed.
                    result:
                      pagination: null
                      set: 3222
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0001:
                  value:
                    code: '401.0001'
                    message: Your session is expired. Please re-login.
                    result:
                      pagination: null
                      set: null
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
                Example-9000:
                  value:
                    code: '401.9000'
                    message: 'You do not have enough permissions to access this feature. '
                    result:
                      pagination: null
                      set: null
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
        '412':
          description: Precondition Failed
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-7000:
                  value:
                    code: '412.7000'
                    message: 'You have supplied an invalid data. Please check releated documentation, fix all your issues and try again. If the problem persists, you can contact our support team.'
                    result:
                      pagination: null
                      set: null
                    sessionToken: 031418d9424af4f81f95610d8fdee1c07943ca970871773bcea2781f1a8dfdfc
      description: |-
        This endpoint is used to create a new multi-choice single answer trivia question entry.

        <!-- theme: warning -->
        > ### WARNING:
        > A trivia editor (NOT ADMIN) can only edit the same question a maximum of 3 times in 120 minutes.

        <!-- theme: danger -->

        > ### ROLE REQUIREMENT
        >
        > This endpoint needs **ROLE_TRIVIA_QUESTION_CREATE** at session. If session also has **ROLE_TRIVIA_QUESTION_APPROVE** role, system creates question with active status (a). If has no, system creates question with waiting approval status (w).

        ### Flow
        ![Flow](https://docs-viaapi.s3.amazonaws.com/flow-charts/admin.post.questions.mc.sa.png)
      security:
        - X-Session-Key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./TriviaModels/TQMultiChoiceSingleVersionCreate.v1.yaml
            examples:
              Example:
                value:
                  uuid: cfc21291-18f6-47cf-b714-ed87d150c076
                  createdAt: '2020-01-20T12:23:24Z'
                  updatedAt: '2020-01-21T21:23:12Z'
                  status: a
                  banner:
                    path: batman-logo.jpg
                    type: i
                  difficultyLevel: 1
                  estimatedReadTime: 50
                  tags:
                    - title: movies
                      icon: movies.png
                      itemCount: 234
                  label:
                    audio: question-223423-2342342-2342.mp3
                    video: question-223423-2342342-2342.mp4
                    image: batman-logo.jpg
                    text: Who among these Hollywood stars have not played the Batman character?
                  choices:
                    - isCorrect: false
                      label:
                        audio: choiceC.wav
                        image: choiceC.jpg
                        text: Jackie Chan
                        video: choicesC.mp4
                    - isCorrect: true
                      label:
                        audio: choiceA.wav
                        image: choiceA.jpg
                        text: Michael Keaton
                        video: choicesA.mp4
                    - isCorrect: false
                      label:
                        audio: choiceB.wav
                        image: choiceB.jpg
                        text: Michael Douglas
                        video: choicesB.mp4
                    - isCorrect: false
                      label:
                        audio: choiceD.wav
                        image: choiceD.jpg
                        text: Denzel Washington
                        video: choicesD.mp4
      tags:
        - Question
externalDocs:
  url: 'https://api.docs.viaapi.com'
components:
  securitySchemes:
    X-Session-Key:
      name: X-Session-Key
      type: apiKey
      in: header
      description: 'This token is required to authenticate "real" users. This token will be assigned and supplied to you dynamically only after successful login using a username-password combination or social media login method. Once - and if - you get this token, you must supplies this token to access data provided by ViaAPI.'
  schemas:
    LoginForm:
      title: LoginForm
      type: object
      description: Represents login form and holds login related information.
      properties:
        email:
          type: string
          description: E-mail of the registered user.
          format: email
          example: member@maildrop.cc
        password:
          type: string
          description: User's password.
        termsAccepted:
          type: boolean
          example: false
          description: Users selection about user agreement.
      required:
        - email
        - password
      x-examples:
        Example:
          username: member@maildrop.cc
          password: 123xyz
          termsAccepted: true
      x-tags:
        - Models
    LoginResponse:
      title: LoginResponse
      type: object
      x-examples:
        Example-1:
          id: 1
          uuid: 861511f1-f3b0-11ea-bc5d-0242ac120005
          status: a
          email: support@viaapi.com
          firstName: Tayfun
          middleName: ''
          lastName: Temizel
          isSuper: 'y'
          roles:
            - ROLE_TQ_MCS_APPROVE
            - ROLE_TQ_MCS_CREATE
            - ROLE_TQ_MCS_DELETE
            - ROLE_TQ_MCS_DELETE_PERM
            - ROLE_TQ_MCS_UPDATE
            - ROLE_TQ_MCS_VIEW
            - ROLE_TQ_TAG_APPROVE
            - ROLE_TQ_TAG_CREATE
            - ROLE_TQ_TAG_DELETE
            - ROLE_TQ_TAG_DELETE_PERM
            - ROLE_TQ_TAG_UPDATE
            - ROLE_TQ_TAG_VIEW
        Example-2:
          id: 32
          uuid: 095be615-a8ad-4c33-8e9c-c7612fbf6c9f
          status: a
          email: support@viaapi.com
          firstName: John
          middleName: Johnny Johnathan
          lastName: Johannesson
          isSuper: true
          roles:
            - ROLE_TQ_MCS_APPROVE
      description: This object holds relevant details about a user after succesfull login.
      x-tags:
        - Models
      properties:
        id:
          type: integer
          minimum: 1
          example: 32
          description: System defined id.
        uuid:
          type: string
          format: uuid
          description: System defined uuid.
        status:
          type: string
          description: Record status.
          enum:
            - a
            - i
            - d
          example: a
        email:
          type: string
          format: email
          example: support@viaapi.com
          description: User's e-mail address.
          nullable: true
        firstName:
          type: string
          example: John
          description: User's first name.
          nullable: true
        middleName:
          type: string
          example: Johnny Johnathan
          description: User's middle name.
          nullable: true
        lastName:
          type: string
          description: User's last name.
          example: Johannesson
          nullable: true
        isSuper:
          type: boolean
          description: |
            Indicates if the user is a super admin or not.
        roles:
          type: array
          minItems: 1
          description: 'full list of available roles can be found here: https://app.archbee.io/public/PdSMT5o4wNDFkh__I9wQp/admin-user-roles'
          items:
            type: string
            enum:
              - ROLE_TQ_MCS_APPROVE
              - ROLE_TQ_MCS_UPDATE
              - ROLE_TQ_TAG_DELETE_PERM
              - ROLE_TQ_TAG_UPDATE
              - ROLE_TQ_TAG_VIEW
      required:
        - status
        - isSuper
