openapi: 3.0.0
tags:
  - name: models
  - name: Panel
  - name: Portal
info:
  title: Portal API
  version: v1.0.0
  license:
    name: Viaapi
    url: 'https://www.viaapi.com/legal/licensing/viaapi'
  contact:
    name: System Administrator
    email: admin@viaapi.com
    url: 'https://www.viaapi.com'
  termsOfService: 'https://www.viaapi.com/legal/global'
  description: 'This documentation covers all endpoints related to portal of ViaAPI.            '
servers:
  - url: 'https://portal.api.viaapi.com/v1'
    description: Production
  - url: 'https://portal.api.dev.viaapi.com/v1'
    description: Development / Testing Server
paths:
  /login:
    parameters: []
    post:
      summary: Login
      operationId: post-portal-login
      responses:
        '200':
          description: When the creation process is successful it returns user data with logged session token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_V1'
              examples:
                Example-0401:
                  value:
                    code: '200.0401'
                    message: You have been successfully logged in.
                    sessionToken: 17ec7d1966adf542cd2c2e1f1800223b0cc4880434942786a089ba6504bca7c7
                    result:
                      pagination: null
                      set:
                        id: '2'
                        uuid: 28d668ce-3df2-11eb-a653-0242ac130002
                        status: a
                        email: support@bodevoffice.com
                        firstName: BO
                        middleName: null
                        lastName: Development
                        mobileNumber: '+905438127108'
                        client:
                          uuid: 11dd3505-3df2-11eb-a653-0242ac130002
                          title: Odit Teknoloji
                          phone:
                            number: '5302926676'
                            countryCode: '+90'
                          email: support@oditteknoloji.com
                          status: a
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_V1'
              examples:
                Example-0002:
                  value:
                    code: '401.0002'
                    message: 'Please check your username and password, and try again.'
                    sessionToken: null
                    result:
                      pagination: null
                      set: null
        '412':
          description: Precondition failed
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0007:
                  value:
                    code: '412.0007'
                    message: '{{ field }} is required. Please supply a value for this parameter.'
                    sessionToken: null
                    result:
                      pagination: null
                      set: null
                Example-9999:
                  value:
                    code: '412.9999'
                    message: 'The value, operands, or options are not valid for the email. Please check related documentation for more information.'
                    sessionToken: null
                    result:
                      pagination: null
                      set: null
                    error:
                      type: validation
                      content: email
      description: Use this endpoint to login for client portal.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login_V1'
            examples:
              Example Request:
                value:
                  email: support@bodevoffice.com
                  password: bodev
                  staySigned: true
        description: Holds Login object.
      tags:
        - Portal
  /register:
    post:
      summary: Register
      operationId: post-portal-register
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0401:
                  value:
                    code: '200.0401'
                    message: You have been successfully logged in.
                    sessionToken: f5d7ebd4b6d8017148651db908737cdb79391416917f66d92aa557e7d539d2ce
                    result:
                      pagination: null
                      set:
                        id: '9'
                        uuid: 94487ecf-1d4a-4d54-bcf0-90fed5674dd7
                        status: a
                        email: john.doe@bodevoffice.com
                        firstName: John
                        middleName: null
                        lastName: Doe
                        mobileNumber: ''
                        client:
                          uuid: 5457499d-1cab-446b-8c2c-ab822820ad06
                          title: John
                          phone: null
                          email: john.doe@bodevoffice.com
                          status: a
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0004:
                  value:
                    code: '401.0004'
                    message: You have registered before with this email. Please try to log in.
                    sessionToken: null
                    result:
                      pagination: null
                      set: null
        '412':
          description: Precondition Failed
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0007:
                  value:
                    code: '412.0007'
                    message: '{{ field }} is required. Please supply a value for this parameter.'
                    sessionToken: null
                    result:
                      pagination: null
                      set: null
                Example-9999:
                  value:
                    code: '412.9999'
                    message: 'The value, operands, or options are not valid for the email. Please check related documentation for more information.'
                    sessionToken: null
                    result:
                      pagination: null
                      set: null
      description: Use this endpoint to register for client portal.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email information
                  format: email
                password:
                  type: string
                  description: Password information
                firstName:
                  type: string
                  description: First Name of user.
                lastName:
                  type: string
                  description: Last Name of user. This field can be null.
              required:
                - email
                - password
                - firstName
            examples:
              example-1:
                value:
                  email: user@example.com
                  password: '1234'
                  firstName: John
                  lastName: Doe
        description: ''
      tags:
        - Portal
  /password/reset:
    post:
      summary: Attempt Reset Password
      operationId: post-portal-password-reset
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0000:
                  value:
                    code: '200.0000'
                    message: Your request has been successfully completed.
                    sessionToken: null
                    result:
                      pagination: null
                      set: true
                Example-0403:
                  value:
                    code: '200.0403'
                    message: We could not find an account with your credentials.
                    sessionToken: null
                    result:
                      pagination: null
                      set: null
        '412':
          description: Precondition Failed
          headers: {}
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-9999:
                  value:
                    code: '412.9999'
                    message: 'The value, operands, or options are not valid for the email. Please check related documentation for more information.'
                    sessionToken: null
                    result:
                      pagination: null
                      set: null
                Example-0007:
                  value:
                    code: '412.0007'
                    message: '"email" is required. Please supply a value for this parameter.'
                    sessionToken: null
                    result:
                      pagination: null
                      set: null
      description: This endpoint creates an password reset recovery so that client can reset password.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
              required:
                - email
            examples:
              Example:
                value:
                  email: user@example.com
        description: Body must contain email.
      tags:
        - Portal
  /profile:
    put:
      summary: Update User Profile Informations
      operationId: post-profile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0000:
                  value:
                    code: '200.0000'
                    message: Your request has been successfully completed.
                    sessionToken: 17ec7d1966adf542cd2c2e1f1800223b0cc4880434942786a089ba6504bca7c7
                    result:
                      pagination: null
                      set:
                        id: '2'
                        uuid: 28d668ce-3df2-11eb-a653-0242ac130002
                        status: a
                        email: support@bodevoffice.com
                        firstName: Test
                        middleName: null
                        lastName: BO
                        mobileNumber: '+905302926676'
            application/xml:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0000:
                  value: ''
        '412':
          description: Precondition Failed
          content:
            application/json:
              schema:
                $ref: ./GenericModels/ApiResponse.v1.yaml
              examples:
                Example-0007:
                  value:
                    code: '412.0007'
                    message: '{{ field }} is required. Please supply a value for this parameter.'
                    sessionToken: 17ec7d1966adf542cd2c2e1f1800223b0cc4880434942786a089ba6504bca7c7
                    result:
                      pagination: null
                      set: null
                Example-9999:
                  value:
                    code: '412.9999'
                    message: 'The value, operands, or options are not valid for the email. Please check related documentation for more information.'
                    sessionToken: 17ec7d1966adf542cd2c2e1f1800223b0cc4880434942786a089ba6504bca7c7
                    result:
                      pagination: null
                      set: null
      description: This endpoint updates user profile.
      security:
        - X-Session-Key: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                firstName:
                  type: string
                lastName:
                  type: string
              required:
                - email
                - firstName
                - lastName
            examples:
              Example:
                value:
                  email: user@example.com
                  firstName: BO
                  lastName: Development
        description: ''
      tags:
        - Portal
externalDocs:
  url: 'https://api.docs.viaapi.com'
components:
  securitySchemes:
    X-Session-Key:
      name: X-Session-Key
      type: apiKey
      in: header
      description: 'This token is required to authenticate "real" users. This token will be assigned and supplied to you dynamically only after successful login using a username-password combination or social media login method. Once - and if - you get this token, you must supplies this token to access data provided by ViaAPI.'
  schemas:
    ApiResponse_V1:
      title: ApiResponse
      type: object
      description: This is the standart response object. All of your request to ViaAPI will return this object.
      properties:
        result:
          $ref: '#./GenericModels/ApiResult.v1.yaml'
        sessionToken:
          type: string
          description: 'This is the session token, and it will only revealed if user logs in the system with username and password, or if an already logged-in user needs to refresh its existing token.'
          example: 1a79a4d60de6718e8e5b326e338ae533
          nullable: true
        code:
          type: string
          example: '200.0000'
          description: 'This is the API''s internal response code. The first part equals to HTTP response code, the second part is used to match more specific causes.'
        message:
          type: string
          description: This is the API's internal response message.
          example: ' Your request has been successfully completed.'
      required:
        - code
        - message
      x-examples:
        Example-200.0000:
          code: '200.0000'
          message: ''
          result:
            pagination:
              isCircular: true
              prevLink: null
              nextLink: offset=10&limit=10
              lastLink: offset=90&limit=10
              firstLink: offset=0&limit=10
              totalItems: 100
              itemsPerPage: 10
              pageCount: 10
              currentPage: 1
          set: true
      x-tags:
        - Models - Generic
    Login_V1:
      title: Login_V1
      type: object
      description: This class is used for login.
      x-examples:
        example-1:
          email: user@example.com
          password: string
          staySigned: null
      properties:
        email:
          type: string
          description: ''
          format: email
        password:
          type: string
        staySigned:
          type: boolean
      required:
        - email
        - password
      x-tags:
        - Models - Generic
